---
title: "Estimates of Republican Support for H.R.8404"
author: "Jack Guan"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Codebook
#   state: district state
#   district: district number
#   member: member last name
#   party: member party
#     0: Democrat
#     1: Republican
#   vote0: vote on H.R.8404 in either July or December
#     0: "no" vote twice
#     1: "yes" vote at least once
#   vote1: vote on H.R.8404 in July
#     0: "no" vote
#     1: "yes" vote
#   vote2: vote on H.R.8404 in December
#     0: "no" vote
#     1: "yes" vote
#   competitive1: Cook PVI score within D+5 to R+5 range 
#     0: outside of range
#     1: inside of range
#   competitive2: Cook PVI score within D+10 to R+10 range 
#     0: outside of range
#     1: inside of range
#   pvi: Cook PVI score
```

```{r}
#Setup
library(estimatr)
data <- read.csv("~/Downloads/hr8404_data.csv")

#Subset to Republicans
gop <- subset(data, party == '1')
```

```{r}
#Vote0 & Competitive1 (D+5 to R+5)
difference_in_means(vote0 ~ competitive1, data = gop, condition1 = '0', condition2 = '1')

#Vote1 & Competitive1 (D+5 to R+5)
difference_in_means(vote1 ~ competitive1, data = gop, condition1 = '0', condition2 = '1')

#Vote2 & Competitive1 (D+5 to R+5)
difference_in_means(vote2 ~ competitive1, data = gop, condition1 = '0', condition2 = '1')
```

```{r}
#Vote0 & Competitive2 (D+10 to R+10)
difference_in_means(vote0 ~ competitive2, data = gop, condition1 = '0', condition2 = '1')

#Vote1 & Competitive2 (D+10 to R+10)
difference_in_means(vote1 ~ competitive2, data = gop, condition1 = '0', condition2 = '1')

#Vote2 & Competitive2 (D+10 to R+10)
difference_in_means(vote2 ~ competitive2, data = gop, condition1 = '0', condition2 = '1')
```