---
title: "Estimates of Republican Support for H.R.8404 (Replication)"
author: "Jack Guan"
date: "`r Sys.Date()`"
output: html_document
---

## Libraries

```{r}
library(estimatr)
```

## Datasets

```{r}
data <- read.csv("~/Downloads/replication-data.csv")
gop <- subset(data, party == '1')
```

## Most Competitive Analysis

```{r}
#Vote0 & Competitive1 (D+5 to R+5)
difference_in_means(vote0 ~ competitive1, data = gop, condition1 = '0', condition2 = '1')

#Vote1 & Competitive1 (D+5 to R+5)
difference_in_means(vote1 ~ competitive1, data = gop, condition1 = '0', condition2 = '1')

#Vote2 & Competitive1 (D+5 to R+5)
difference_in_means(vote2 ~ competitive1, data = gop, condition1 = '0', condition2 = '1')
```

# Less Competitive Analysis

```{r}
#Vote0 & Competitive2 (D+10 to R+10)
difference_in_means(vote0 ~ competitive2, data = gop, condition1 = '0', condition2 = '1')

#Vote1 & Competitive2 (D+10 to R+10)
difference_in_means(vote1 ~ competitive2, data = gop, condition1 = '0', condition2 = '1')

#Vote2 & Competitive2 (D+10 to R+10)
difference_in_means(vote2 ~ competitive2, data = gop, condition1 = '0', condition2 = '1')
```
